name: Deploy Scraper to VPS

on:
  push:
    branches:
      - main
    paths:
      # TODO add shared/ path here too once you set up monorepo
      - "event-scraper/**"
      - ".github/workflows/deploy-scraper.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          script: |
            cd ~/programming/boon-we-gig/event-scraper
            git pull origin main
            ./scripts/deploy.sh
